### ISSUE TITLE
Bug in CSS - use of initial keyword

### ISSUE THREAD

**Issue by mitja-p** [AngleSharp/AngleSharp#76]
Hi,

I found some bugs when parsing / generating css.

Sample css:

``` css
#rule1 { border:1px solid #BBCCEB; border-top:none }
#rule2 { background:url(/_static/img/bx_tile.gif) top left repeat-x; }
```

This when loaded and then saved again produces invalid css:

``` css
#rule1 { border-width: initial 1px 1px; border-style: none solid solid; border-color: initial rgba(187, 204, 235, 1) rgba(187, 204, 235, 1); }
#rule2 { background: url("/_static/img/bx_tile.gif") top left repeat-x initial initial initial initial; }
```

As far as I tested it hasn't been fixed yet.

One more thing. Is there any special reason why 0.8. and 0.8.1. were not tagged in repository? It would be nice to have a tag there so we can take out a stable version.

Regards,
Mitja

**Comment by mitja-p** [comment]
One more:

``` css
ol,ul{list-style:none}
```

gets converted to

``` css
ol,ul { list-style: initial initial initial; }
```
